### ISSUE TITLE
Fehlermeldung ausgeben falls Modul nicht im Semester stattfindet. 

### ISSUE THREAD

**Issue by joshuabeny1999** [unkelhoebbi/semester-scheduler#6]
Keine Ahnung ob man die Info ob das Modul im Frühlingssemester oder Herbstsemester stattfindet ebenfalls Crawlen kann. Dann könnte man die Modulauswahl weiter einschränken pro Semester und so eine bessere Planung anbieten. Nicht das man dann ein Plan erstellt, der gar nicht funktioniert.

**Comment by jeremystucki** [comment]
I think this will need further discussion.

To make this work we would need to specify exactly which semester you're planning, not only the relative number ("HS21" vs "3").
This would also make it really difficult to account for students who started before the new regime, since we would need to add all the transitions from old to new.

This is certainly not impossible, but would require quite a lot of manual work to collect the information from all the different sources (email, MS teams, etc.).

I think if we would do this it would greatly increase the attractiveness of the planner.
This would also solve #5 as the modules differ by the semester they were offered in.

**Comment by jeremystucki** [comment]
So I had a quick look at the data and it's nearly impossible to figure this stuff out.

Example Web Engineering 2:
It was offered in HS21, but there is no mention of this here: https://studien.rj.ost.ch/allModules/38945_M_WE2.html

So I don't think we can do this reliably without creating a lot of false negatives.

**Comment by joshuabeny1999** [comment]
I guess one reliable source would be the "Musterstundenpläne". But pdf crawling would be hard. So it is possible. But I guess we need to move this feature to a later stage. And manually data population via crowd would be an option but then it should be optional and not blocking to plan differently. Maybe with a checkbox to use this crowd data for planning and so manually enable the restrictions.

Freundliche Grüsse
Joshua Hürzeler
Am 6. Feb. 2022, 10:51 +0100 schrieb Jeremy Stucki ***@***.***>:
